In [1]:
from __future__ import print_function, division
#from future.utils import iteritems
from builtins import range, input
from get_data import xor_data
from get_data import donut_data
from get_data import fig_data
# Note: you may need to update your version of future
# sudo pip install -U future


import numpy as np
#from util import get_data, get_xor, get_donut
from datetime import datetime

In [2]:
Xtrain,Ytrain,Xtest,Ytest=fig_data(limit=10000,ratio=0.5,seed=100)
# try donut and xor
X1,Y1=Xtrain,Ytrain

In [3]:
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier()


In [4]:
dtree=dtree.fit(Xtrain,Ytrain)

In [5]:
predictions = dtree.predict(Xtrain)

In [6]:
from sklearn.metrics import classification_report,confusion_matrix

In [7]:
print(classification_report(Ytrain,predictions))

             precision    recall  f1-score   support

        0.0       1.00      1.00      1.00       497
        1.0       1.00      1.00      1.00       537
        2.0       1.00      1.00      1.00       506
        3.0       1.00      1.00      1.00       482
        4.0       1.00      1.00      1.00       468
        5.0       1.00      1.00      1.00       467
        6.0       1.00      1.00      1.00       490
        7.0       1.00      1.00      1.00       515
        8.0       1.00      1.00      1.00       512
        9.0       1.00      1.00      1.00       526

avg / total       1.00      1.00      1.00      5000



In [8]:
print(confusion_matrix(Ytrain,predictions))

[[497   0   0   0   0   0   0   0   0   0]
 [  0 537   0   0   0   0   0   0   0   0]
 [  0   0 506   0   0   0   0   0   0   0]
 [  0   0   0 482   0   0   0   0   0   0]
 [  0   0   0   0 468   0   0   0   0   0]
 [  0   0   0   0   0 467   0   0   0   0]
 [  0   0   0   0   0   0 490   0   0   0]
 [  0   0   0   0   0   0   0 515   0   0]
 [  0   0   0   0   0   0   0   0 512   0]
 [  0   0   0   0   0   0   0   0   0 526]]


In [13]:
predictions_ = dtree.predict(Xtest)
print(classification_report(Ytest,predictions_))
print(confusion_matrix(Ytest,predictions_))

             precision    recall  f1-score   support

        0.0       0.86      0.86      0.86       505
        1.0       0.89      0.94      0.91       560
        2.0       0.70      0.65      0.68       452
        3.0       0.72      0.70      0.71       515
        4.0       0.81      0.78      0.79       488
        5.0       0.67      0.68      0.67       487
        6.0       0.83      0.81      0.82       509
        7.0       0.81      0.83      0.82       514
        8.0       0.68      0.68      0.68       475
        9.0       0.70      0.74      0.72       495

avg / total       0.77      0.77      0.77      5000

[[433   1   9   3   5  26   7   8   5   8]
 [  0 524   4   1   2   3   8   2   7   9]
 [ 19  11 295  19   8  14  16  25  27  18]
 [  9   8  25 362   6  47   6  12  27  13]
 [  5   6   3   3 380   8   9  12  14  48]
 [ 15   4  14  48   8 330  23   7  20  18]
 [ 11   2  24   7  16  15 411   2  14   7]
 [  2   8  14  14   5   8   2 428  10  23]
 [  6  18  26  30

In [9]:
import graphviz 
#from sklearn.tree import export_graphviz
from sklearn import tree


In [10]:
clf = tree.DecisionTreeClassifier()

In [11]:

clf = clf.fit(Xtrain, Ytrain)
dot_data = tree.export_graphviz(clf, out_file=None) 
graph = graphviz.Source(dot_data) 
graph.render("MNIST")

'MNIST.pdf'

In [12]:
#X1,Y1 10 classes
from sklearn.tree import DecisionTreeClassifier
dtree_ = DecisionTreeClassifier()
dtree_=dtree_.fit(X1,Y1)
predictions_ = dtree_.predict(X1)
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(Y1,predictions_))
print(confusion_matrix(Y1,predictions_))

             precision    recall  f1-score   support

        0.0       1.00      1.00      1.00       497
        1.0       1.00      1.00      1.00       537
        2.0       1.00      1.00      1.00       506
        3.0       1.00      1.00      1.00       482
        4.0       1.00      1.00      1.00       468
        5.0       1.00      1.00      1.00       467
        6.0       1.00      1.00      1.00       490
        7.0       1.00      1.00      1.00       515
        8.0       1.00      1.00      1.00       512
        9.0       1.00      1.00      1.00       526

avg / total       1.00      1.00      1.00      5000

[[497   0   0   0   0   0   0   0   0   0]
 [  0 537   0   0   0   0   0   0   0   0]
 [  0   0 506   0   0   0   0   0   0   0]
 [  0   0   0 482   0   0   0   0   0   0]
 [  0   0   0   0 468   0   0   0   0   0]
 [  0   0   0   0   0 467   0   0   0   0]
 [  0   0   0   0   0   0 490   0   0   0]
 [  0   0   0   0   0   0   0 515   0   0]
 [  0   0   0   0

In [71]:
import graphviz 
#from sklearn.tree import export_graphviz
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X1, Y1)
dot_data = tree.export_graphviz(clf, out_file=None) 
graph = graphviz.Source(dot_data) 
graph.render("MNIST_multiclass")

'MNIST_multiclass.pdf'